-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: clang-format
    
    repos:
-   repo: https://github.com/DevOpsOperationFacilitator/javaloginapp
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json